---
- name: Ensure site is up to date
  sudo: true
  yum: name=* state=latest
- name: Install Base dependencies
  sudo: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    base_dependencies

- name: Get Ruby
  get_url:
    url: "{{ ruby.src_url }}/{{ ruby.version.major }}.{{ ruby.version.minor }}/ruby-{{ ruby.version.major }}.{{ ruby.version.minor }}.{{ ruby.version.patch }}.tar.gz"
    dest: /tmp/ruby.tar.gz

- name: Unpack Ruby
  command: tar xfz ruby.tar.gz -C /root/ruby
  args:
    chdir: /tmp
    creates: /root/ruby

- name: Configure Ruby
  command: ./configure
  args:
    chdir: /root/ruby

- name: Build Ruby
  command: make
  args:
    chdir: /root/ruby

- name: Install Jekyll
  sudo: true
  gem:
    name: jekyll
    state: latest
