---
- name: Ensure site is up to date (RedHat)
  sudo: true
  yum: name=* state=latest
  when: ansible_os_family == 'RedHat'

# Skipping this because it gives some funky errors on Travis
#- name: Ensure site is up to date (Debian)
#  sudo: true
#  apt: name=* state=latest
#  when: ansible_os_family == 'Debian'

- name: Install Base dependencies (RedHat)
  sudo: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
     base_dependencies[ansible_os_family]
  when: ansible_os_family == 'RedHat'

- name: Install Base dependencies (Debian)
  sudo: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    base_dependencies[ansible_os_family]
  when: ansible_os_family == 'Debian'


- name: Get Ruby
  get_url:
    url: "{{ ruby.src_url }}/{{ ruby.version.major }}.{{ ruby.version.minor }}/ruby-{{ ruby.version.major }}.{{ ruby.version.minor }}.{{ ruby.version.patch }}.tar.gz"
    dest: /tmp/ruby.tar.gz
    timeout: 60

- name: Unpack Ruby
  command: tar xfz ruby.tar.gz -C /root/
  sudo: true
  args:
    chdir: /tmp
    creates: "/root/ruby-{{ ruby.version.major }}.{{ ruby.version.minor }}.{{ ruby.version.patch }}"

- name: Configure Ruby
  sudo: true
  command: "./configure --prefix={{ ruby.install_path }}"
  args:
    chdir: "/root/ruby-{{ ruby.version.major }}.{{ ruby.version.minor }}.{{ ruby.version.patch }}"

- name: Build Ruby
  command: make install
  sudo: true
  environment: { CFLAGS: "{{ cflags }}"}
  args:
    chdir: "/root/ruby-{{ ruby.version.major }}.{{ ruby.version.minor }}.{{ ruby.version.patch }}"

- name: Install Jekyll
  sudo: true
  gem:
    name: jekyll
    state: latest
