---
- name: Install Jekyll dependencies
  sudo: true
  yum:
    name: "{{ item }}"
  with_items:
    "{{ jekyll_dependencies }}"

- name: Install Jekyll
  sudo: true
  gem:
    name: jekyll
    state: latest
