---
- name: checkout gh-pages
  git:
    repo: https://github.com/SAGridOps/
    clone: yes
    version: gh-pages
    dest: /root/gh-pages

- name: Build the site
  command: jekyll build
    chdir: /root/gh-pages

- name: debug apache
  debug: var="{{ web_server.ansible_os_family.name }}"

- name: Ensure that Apache is started
  service:
    name: "{{ web_server.ansible_os_family.name }}"
    state: started
