---
- name: checkout gh-pages
  command: git checkout gh-pages
  args:
    chdir: /root/CA-website

- name: clean up symlinks
  file:
    name: roles/CA-Jekyll-role
    state: absent

- name: Build the site
  command: jekyll build

- name: debug apache
  debug: var="{{ web_server.ansible_os_family.name }}"
  
- name: Ensure that Apache is started
  service:
    name: "{{ web_server.ansible_os_family.name }}"
    state: started
