# Doesn't use containers yet, so we need to reproduce the container.
language: bash
branches:
  only:
    - master
    - gh-pages
before_install:
- echo $PWD
# We need to install Ansible
- sudo apt-get clean all && sudo apt-get -y update
- sudo apt-get install -y python-yaml python-jinja2 python-httplib2 python-keyczar python-paramiko python-setuptools git python-pip
- sudo mkdir /etc/ansible/
- echo $'[local]\nlocalhost\n' | sudo tee --append /etc/ansible/hosts
- sudo mkdir /opt/ansible/
- sudo git clone --recursive https://github.com/ansible/ansible.git /opt/ansible/ansible
- cd /opt/ansible/ansible
- sudo git submodule update --init
env:
- PATH=/opt/ansible/ansible/bin:/bin:/usr/bin:/sbin:/usr/sbin:$PATH PYTHONPATH=/opt/ansible/ansible/lib:$PYTHONPATH ANSIBLE_LIBRARY=/opt/ansible/ansible/library
install:
- echo "$PWD" ; ls -lht
- cd $TRAVIS_BUILD_DIR
- mkdir -p roles
- mv  CA-Jekyll-role roles/
# We have to put all this stuff in the "roles" directory
- ansible-playbook -c local CA.yml
notifications:
slack:
rooms:
- africa-arabia-roc:8bySc6HbbEvvxPYqg0Z56Xdk#appdevops
